server:
  port: 8201 
---   
spring:
  profiles:
    active:  dev
    application:
      name: mircoservicecloud-config-client
eureka:
   client:
       service-url:
        defaultZone: http://eureka-dev.com:7001/eureka/
       
---
server:
  port: 8202
spring:
  profiles:
    active:  test
    application:
      name: mircoservicecloud-config-client
eureka:
   client:
       service-url:
        defaultZone: http://eureka-dev.com:7001/eureka/
       
